/**
 * Cross-device sync via a private GitHub Gist, called directly from the
 * browser with your own personal access token — the same pattern as the
 * Claude Vision key: nothing goes through a server of this app's own.
 *
 * A classic PAT with only the `gist` scope is enough (fine-grained tokens
 * do not currently cover the Gists API at all, so this deliberately does not
 * try to support them).
 */

export class SyncError extends Error {}

const FILE_NAME = 'performace-data.json';
const API = 'https://api.github.com';

function headers(token: string): HeadersInit {
  return {
    Authorization: `Bearer ${token.trim()}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  };
}

async function call(url: string, init: RequestInit, token: string): Promise<Response> {
  let res: Response;
  try {
    res = await fetch(url, { ...init, headers: headers(token) });
  } catch {
    throw new SyncError('Could not reach GitHub — check your connection.');
  }
  if (!res.ok) {
    if (res.status === 401) throw new SyncError('That GitHub token was rejected. Check it in Settings.');
    if (res.status === 404) {
      throw new SyncError('That gist was not found — it may have been deleted, or the token lacks gist access.');
    }
    if (res.status === 403) throw new SyncError('GitHub rate-limited or blocked this request. Try again shortly.');
    const body = await res.text().catch(() => '');
    throw new SyncError(`GitHub returned an error (${res.status}). ${body.slice(0, 200)}`);
  }
  return res;
}

/** Creates the one gist a device's sync will live in from then on. */
export async function createSyncGist(token: string, content: string): Promise<string> {
  const res = await call(
    `${API}/gists`,
    {
      method: 'POST',
      body: JSON.stringify({
        description: 'Performace sync data — generated by the app, not meant to be edited by hand.',
        public: false,
        files: { [FILE_NAME]: { content } },
      }),
    },
    token,
  );
  const data = (await res.json()) as { id: string };
  return data.id;
}

/** Pulls the current mirrored state down. Null if the gist has no data file yet. */
export async function fetchSyncGist(token: string, gistId: string): Promise<string | null> {
  const res = await call(`${API}/gists/${gistId}`, { method: 'GET' }, token);
  const data = (await res.json()) as { files?: Record<string, { content?: string }> };
  return data.files?.[FILE_NAME]?.content ?? null;
}

/** Overwrites the mirrored state with this device's current copy. */
export async function pushSyncGist(token: string, gistId: string, content: string): Promise<void> {
  await call(
    `${API}/gists/${gistId}`,
    { method: 'PATCH', body: JSON.stringify({ files: { [FILE_NAME]: { content } } }) },
    token,
  );
}
